### ISSUE TITLE
北海道胆振東部地震 2018/09/06 

### ISSUE THREAD

**Issue by mapconcierge** [dronebird/mapping#2]
# Tasking Manager 

* [x] #5188 - 北海道胆振東部地震2018厚真川地区(9/6撮影)  https://tasks.hotosm.org/project/5188

* [ ] #5220 - 北海道胆振東部地震2018厚真地区(9/6-8国土地理院撮影) https://tasks.hotosm.org/project/5220

* [ ] #5221 - 北海道胆振東部地震2018厚真東部地区(9/11国土地理院撮影) 
https://tasks.hotosm.org/project/5221

* [ ] #5228 - 北海道胆振東部地震2018安平・厚真西部地区(9/11国土地理院撮影) 
https://tasks.hotosm.org/project/5228

# 使用可能データ

* 地理院地図タイル一覧
https://maps.gsi.go.jp/development/ichiran.html#t20180906hokkaido_atsumtoubu_0911do

* 9/6, 8 国土地理院空撮データ
https://gist.github.com/mapconcierge/ee27628c9d7f996abbada7c820057d6b

[厚真地区（9:6,8撮影）国土地理院撮影データエリア.zip](https://github.com/dronebird/mapping/files/2373684/9.6.8.zip)

* 9/11 国土地理院空撮データ
#平成30年北海道胆振東部地震 関連 9月11日に撮影した厚真東部地区（北海道勇払郡厚真町・むかわ町、沙流郡平取町）の空中写真（垂直写真）を地理院地図で公開しました。 https://twitter.com/GSI_chiriin

* 厚真東部地区
https://gist.github.com/mapconcierge/bcc88de399e9287e4b4cd31278cd9102

* 厚真西部地区
https://gist.github.com/mapconcierge/9fac6e01d95ece0637fdb248377ac426

**Comment by mapconcierge** [comment]
* WorldView imagery from DigitalGlobe via 酪農学園大学
![41598648_337002090380767_3439604759202365440_n](https://user-images.githubusercontent.com/416977/45457307-50af2d80-b729-11e8-8e1c-7e90955b5b4e.jpg)
